'use client';

import {
  ArrowDownRight, ArrowRight, BarChart3, BriefcaseBusiness, CandlestickChart,
  Check, ChevronDown, CircleGauge, Compass, GraduationCap, Landmark, Menu,
  ShieldCheck, Target, TrendingUp, X,
} from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

const services = [
  ['01', BarChart3, 'Market Analysis & Research', 'Daily technical and fundamental market research, organised to support informed decisions.', ['Pre-market & post-market reports', 'Sector rotation & thematic analysis', 'NSE/BSE stock screening']],
  ['02', CandlestickChart, 'Intraday & BTST Calls', 'Structured intraday and buy-today-sell-tomorrow research calls with clear trade parameters.', ['Entry, target & stop-loss levels', 'Timely Telegram / WhatsApp alerts', 'Pre-market market view']],
  ['03', Target, 'Options Trading Advisory', 'Options research for index and stock participants, with clarity on strike selection and risk.', ['Daily options trade setups', 'Strike & expiry guidance', 'Greeks and strategy analysis']],
  ['04', TrendingUp, 'Index Trading', 'Research-led Nifty and Bank Nifty ideas designed around defined risk and market context.', ['Nifty positional research', 'Bank Nifty strategies', 'Weekly index outlook']],
  ['05', Compass, 'Delivery & Swing Trading', 'Curated delivery and swing trade research for investors seeking quality opportunities.', ['Delivery picks each month', 'Fundamental + technical view', 'Sector rotation alerts']],
  ['06', Landmark, 'Commodity Advisory (MCX)', 'Macro-aware commodity research across Gold, Silver, Crude Oil and Natural Gas.', ['MCX research calls', 'Global macro analysis', 'Weekly commodity outlook']],
  ['07', ShieldCheck, 'Risk Management Training', 'Build a more resilient approach with practical capital-protection and position-sizing principles.', ['Position sizing frameworks', 'Stop-loss techniques', 'Portfolio diversification']],
  ['08', GraduationCap, 'Learning Programmes & Courses', 'Structured learning tracks that take market participants from core concepts to applied analysis.', ['Foundation to advanced tracks', 'Live group sessions', 'Recorded learning access']],
  ['09', BriefcaseBusiness, 'Portfolio Management Guidance', 'Educational guidance to help you understand allocation, diversification and review disciplines.', ['Model portfolio concepts', 'Portfolio review framework', 'Rebalancing education']],
] as const;

const courses = [
  ['Beginner', 'Stock Market Foundation', '40 hours · 2,400+ learners', 'https://images.unsplash.com/photo-1770626894265-bdb99db109f1?auto=format&fit=crop&w=1200&q=85', 'Build confident market basics: demat accounts, order types, market terminology, fundamental analysis and valuation essentials.'],
  ['Intermediate', 'Technical Analysis Masterclass', '60 hours · 1,800+ learners', 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=1200&q=85', 'Learn to read price action, charts, patterns and indicators in a disciplined, repeatable research process.'],
  ['Advanced', 'Advanced Trading Strategies', '90 hours · 940+ learners', 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=85', 'Explore derivatives, options strategies, risk frameworks and portfolio thinking for experienced market participants.'],
] as const;
const navigation = [['Home', '#home'], ['About', '#about'], ['Research Services', '#services'], ['Learning', '#learning']];

function Brand() { return <a className="brand" href="#home" aria-label="Rajesh Nivesh home"><img src="/rajesh-nivesh-logo.png" alt="" /><span className="brand-name"><b>Rajesh</b><em>निवेश</em></span></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [servicesVisible, setServicesVisible] = useState(false);
  const [showAllSolutions, setShowAllSolutions] = useState(false);
  const servicesRef = useRef<HTMLElement | null>(null);
  useEffect(() => {
    const node = servicesRef.current;
    if (!node) return;
    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) { setServicesVisible(true); observer.disconnect(); }
    }, { threshold: 0.2 });
    observer.observe(node);
    return () => observer.disconnect();
  }, []);
  return <main className="reference-page">
    <section id="home" className="hero-reference"><header className="site-header"><Brand /><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</nav><div className="hero-actions"><a className="quote-button" href="#services">Explore research <ArrowRight size={16} /></a><span className="grid-menu" aria-hidden="true">⠿</span></div><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>{menuOpen && <nav className="mobile-nav" aria-label="Mobile navigation">{navigation.map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav>}</header><div className="hero-background" /><div className="hero-copy-reference"><h1>Navigate Markets<br />With <span>Research-Led</span><br />Clarity &amp; Discipline</h1><p><b>✳</b> Professional market research for participants who value preparation, process and informed decision-making.</p><a className="lime-button" href="#services">Explore services <ArrowRight size={17} /></a></div><div className="hero-person"><img src="https://images.unsplash.com/photo-1770626894265-bdb99db109f1?auto=format&fit=crop&w=1500&q=90" alt="Indian financial professional" /></div><button className="slider-arrow arrow-left" aria-label="Previous slide"><ArrowDownRight /></button><button className="slider-arrow arrow-right" aria-label="Next slide"><ArrowRight /></button><div className="hero-scroll">Scroll down <ArrowDownRight /></div><div className="experience-card"><div><strong>16<sup>+</sup></strong><p>Years of market<br />learning &amp; research</p></div><img src="https://images.unsplash.com/photo-1770626894265-bdb99db109f1?auto=format&fit=crop&w=900&q=85" alt="" /></div></section>
    <section id="about" className="about-reference"><div className="about-media"><div className="about-image"><img src="https://images.unsplash.com/photo-1587614382346-4ec70e388b28?auto=format&fit=crop&w=1200&q=85" alt="Indian professionals discussing market research" /></div><div className="about-arrows"><button aria-label="Previous"><ArrowDownRight /></button><button aria-label="Next"><ArrowRight /></button></div><div className="happy-card"><strong>1M<sup>+</sup></strong><p>Research views<br />and learning touchpoints</p></div></div><div className="about-reference-copy"><p className="orange-kicker"><b>✳</b> About Rajesh Nivesh</p><h2>Elevating your market<br />process with <strong>clarity.</strong></h2><p>Rajesh Nivesh is a dedicated platform for serious market participants who believe in informed decision-making over speculation. Led by SEBI Registered Research Analyst Rajesh Sharma, the platform delivers high-quality market insights and trading education.</p><div className="about-roles"><div><span><CircleGauge size={22} /></span><b>Technical &amp; Fundamental<br />Research</b></div><div><span><ShieldCheck size={22} /></span><b>Risk-Controlled Trading<br />Perspectives</b></div></div><div className="about-points"><p>✿ Daily market context and structured research</p><p>✿ Learning designed around discipline, not hype</p></div><a className="dark-button" href="#services">More about <ArrowRight size={17} /></a></div></section>
    <section ref={servicesRef} id="services" className={`services-reference ${servicesVisible ? 'is-visible' : ''}`}><div className="solutions-shell"><div className="solutions-heading"><div><p className="orange-kicker"><b>✳</b> Our solutions</p><h2><span>Providing the best</span> <strong>solutions</strong><br />for your business</h2></div><button className="view-services" type="button" aria-expanded={showAllSolutions} onClick={() => setShowAllSolutions(!showAllSolutions)}>{showAllSolutions ? 'Show featured services' : 'View all services'} <ArrowRight size={14} /></button></div><div className="solution-progress" aria-hidden="true"><i /><span /></div><div className="solutions-cards">{services.slice(0, showAllSolutions ? services.length : 3).map(([number, Icon, title, description], index) => <article key={title} className="solution-card" style={{ '--delay': `${index * 110}ms` } as React.CSSProperties}><div className="solution-image"><img src="https://images.unsplash.com/photo-1770626894265-bdb99db109f1?auto=format&fit=crop&w=1200&q=85" alt="Indian financial professional" /></div><span className="solution-symbol">{index === 0 ? <Target size={43} strokeWidth={2.35} /> : <Icon size={41} strokeWidth={2.2} />}</span><div className="solution-content"><h3>{title}</h3><p>{description}</p><a href="#disclaimer"><i />Learn more <ArrowRight size={16} /></a></div></article>)}</div></div></section>
    <section id="learning" className="learning section-shell"><div className="learning-heading"><div><div className="section-kicker"><span>03</span> Learning programmes</div><h2>Choose your<br /><i>learning path.</i></h2></div><p>Carefully crafted programmes for each stage of your market journey—from essential foundations to more advanced strategy work.</p></div><div className="courses-grid">{courses.map(([level, title, meta, image, description], index) => <article className="course-card" key={title}><div className="course-image"><img src={image} alt="" /><span>{level}</span><b>0{index + 1}</b></div><div className="course-body"><p className="course-meta">{meta}</p><h3>{title}</h3><p>{description}</p><a className="course-link" href="#disclaimer">Explore programme <ArrowRight size={16} /></a></div></article>)}</div></section>
    <section className="cta-section"><div className="cta-grid"><div><p className="eyebrow"><span /> Start with clarity</p><h2>Make room for a<br /><i>better market process.</i></h2></div><div><p>Explore the research service or learning programme that fits where you are today. No shortcuts—just a more structured way to engage with the markets.</p><a className="button button-light" href="#services">View all services <ArrowRight /></a></div></div><div className="cta-graphic" aria-hidden="true">RN</div></section>
    <footer id="disclaimer" className="footer section-shell"><Brand /><div className="footer-grid"><p>Rajesh Nivesh provides research and education designed to support informed market participation.</p><p><strong>Important:</strong> Investments in securities market are subject to market risks. Read all the related documents carefully before investing. Past performance is not indicative of future results.</p><p>SEBI Registered Research Analyst<br />Registration No. INH000026628</p></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Rajesh Nivesh. All rights reserved.</span><span>Privacy · Terms · Disclosures</span></div></footer>
  </main>;
}
