'use client';

import {
  ArrowDownRight, ArrowRight, BarChart3, BriefcaseBusiness, CandlestickChart,
  Check, ChevronDown, CircleGauge, Compass, GraduationCap, Landmark, Menu,
  ShieldCheck, Target, TrendingUp, X,
} from 'lucide-react';
import { useState } from 'react';

const services = [
  ['01', BarChart3, 'Market Analysis & Research', 'Daily technical and fundamental market research, organised to support informed decisions.', ['Pre-market & post-market reports', 'Sector rotation & thematic analysis', 'NSE/BSE stock screening']],
  ['02', CandlestickChart, 'Intraday & BTST Calls', 'Structured intraday and buy-today-sell-tomorrow research calls with clear trade parameters.', ['Entry, target & stop-loss levels', 'Timely Telegram / WhatsApp alerts', 'Pre-market market view']],
  ['03', Target, 'Options Trading Advisory', 'Options research for index and stock participants, with clarity on strike selection and risk.', ['Daily options trade setups', 'Strike & expiry guidance', 'Greeks and strategy analysis']],
  ['04', TrendingUp, 'Index Trading', 'Research-led Nifty and Bank Nifty ideas designed around defined risk and market context.', ['Nifty positional research', 'Bank Nifty strategies', 'Weekly index outlook']],
  ['05', Compass, 'Delivery & Swing Trading', 'Curated delivery and swing trade research for investors seeking quality opportunities.', ['Delivery picks each month', 'Fundamental + technical view', 'Sector rotation alerts']],
  ['06', Landmark, 'Commodity Advisory (MCX)', 'Macro-aware commodity research across Gold, Silver, Crude Oil and Natural Gas.', ['MCX research calls', 'Global macro analysis', 'Weekly commodity outlook']],
  ['07', ShieldCheck, 'Risk Management Training', 'Build a more resilient approach with practical capital-protection and position-sizing principles.', ['Position sizing frameworks', 'Stop-loss techniques', 'Portfolio diversification']],
  ['08', GraduationCap, 'Learning Programmes & Courses', 'Structured learning tracks that take market participants from core concepts to applied analysis.', ['Foundation to advanced tracks', 'Live group sessions', 'Recorded learning access']],
  ['09', BriefcaseBusiness, 'Portfolio Management Guidance', 'Educational guidance to help you understand allocation, diversification and review disciplines.', ['Model portfolio concepts', 'Portfolio review framework', 'Rebalancing education']],
] as const;

const courses = [
  ['Beginner', 'Stock Market Foundation', '40 hours · 2,400+ learners', 'https://images.unsplash.com/photo-1770626894265-bdb99db109f1?auto=format&fit=crop&w=1200&q=85', 'Build confident market basics: demat accounts, order types, market terminology, fundamental analysis and valuation essentials.'],
  ['Intermediate', 'Technical Analysis Masterclass', '60 hours · 1,800+ learners', 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=1200&q=85', 'Learn to read price action, charts, patterns and indicators in a disciplined, repeatable research process.'],
  ['Advanced', 'Advanced Trading Strategies', '90 hours · 940+ learners', 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=85', 'Explore derivatives, options strategies, risk frameworks and portfolio thinking for experienced market participants.'],
] as const;
const navigation = [['Home', '#home'], ['About', '#about'], ['Research Services', '#services'], ['Learning', '#learning']];

function Brand() { return <a className="brand" href="#home" aria-label="Rajesh Nivesh home"><span className="brand-crest" aria-hidden="true" /><span className="brand-copy"><strong>Rajesh</strong><em>निवेश</em></span></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main>
    <div className="announcement"><span /> SEBI Registered Research Analyst · Reg. No. INH000026628 <a href="#disclaimer">Read disclosures <ArrowRight size={13} /></a></div>
    <header className="site-header"><Brand /><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</nav><a className="header-action" href="#services">Explore research <ArrowDownRight size={16} /></a><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>{menuOpen && <nav className="mobile-nav" aria-label="Mobile navigation">{navigation.map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav>}</header>
    <section id="home" className="hero"><div className="hero-noise" /><div className="hero-content reveal-up"><p className="eyebrow"><span /> Research for the Indian market</p><h1>See the market<br />with <i>more clarity.</i></h1><p className="hero-copy">Rajesh Nivesh brings research, trading education and risk-aware market perspectives together—so you can move beyond noise and towards informed participation.</p><div className="hero-buttons"><a className="button button-gold" href="#services">Explore our services <ArrowRight /></a><a className="text-button" href="#about">Our approach <ArrowDownRight /></a></div><div className="hero-trust"><div className="avatars"><span>R</span><span>A</span><span>J</span></div><p><strong>Research-led. Risk-aware.</strong><br />Built for serious market participants.</p></div></div><div className="hero-visual reveal-right"><div className="hero-photo-wrap"><img src="https://images.unsplash.com/photo-1770626894265-bdb99db109f1?auto=format&fit=crop&w=1500&q=90" alt="Indian market professional at work" /></div><div className="chart-lines" aria-hidden="true"><span /><span /><span /><span /><span /></div><div className="market-card market-card-top"><span className="market-label">Market lens</span><strong>NIFTY 50</strong><b>+0.84%</b><small>Data-led context, not speculation</small></div><div className="market-card market-card-bottom"><CircleGauge /><div><span>Risk first</span><strong>Defined & disciplined</strong></div></div><div className="hero-logo-plaque"><img src="/rajesh-nivesh-logo.png" alt="Rajesh Nivesh logo" /></div><div className="orb orb-one" /><div className="orb orb-two" /></div><a className="scroll-cue" href="#about"><span>Scroll to discover</span><ChevronDown /></a></section>
    <section className="ticker" aria-label="Research areas"><div><span>Equity Research</span><b>✦</b><span>Technical Analysis</span><b>✦</b><span>Risk Management</span><b>✦</b><span>Market Education</span><b>✦</b><span>Equity Research</span><b>✦</b><span>Technical Analysis</span><b>✦</b><span>Risk Management</span><b>✦</b></div></section>
    <section id="about" className="about section-shell"><div className="section-kicker"><span>01</span> About Rajesh Nivesh</div><div className="about-grid"><div><h2>Informed decisions.<br /><i>Never speculation.</i></h2></div><div className="about-copy"><p>Rajesh Nivesh is a dedicated platform for serious market participants who believe in informed decision-making over speculation. Led by <strong>SEBI Registered Research Analyst Rajesh Sharma</strong>, the platform delivers high-quality stock market insights, trading strategies and investment education.</p><p>Our work centres on technical and fundamental analysis, risk-controlled trading and consistent performance over hype—helping participants build a more knowledgeable relationship with the market.</p><a className="inline-link" href="#services">Discover our research framework <ArrowRight /></a></div></div><div className="principles">{[['01', 'Registered research', 'Research delivered with regulatory accountability.'], ['02', 'Risk-controlled thinking', 'Capital protection remains part of every market conversation.'], ['03', 'Education before action', 'Clarity and learning come before market participation.']].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="services" className="services"><div className="section-shell"><div className="services-intro"><div><div className="section-kicker light"><span>02</span> What we offer</div><h2>Research that meets you<br />where <i>your goals</i> are.</h2></div><p>Explore thoughtfully structured research and learning solutions across the Indian markets.</p></div><div className="services-grid">{services.map(([number, Icon, title, description, points]) => <article key={title} className="service-card"><div className="service-top"><span>{number}</span><Icon size={24} strokeWidth={1.5} /></div><h3>{title}</h3><p>{description}</p><ul>{points.map(point => <li key={point}><Check size={14} />{point}</li>)}</ul><a href="#disclaimer" aria-label={`Learn about ${title}`}>Learn more <ArrowRight size={16} /></a></article>)}</div></div></section>
    <section id="learning" className="learning section-shell"><div className="learning-heading"><div><div className="section-kicker"><span>03</span> Learning programmes</div><h2>Choose your<br /><i>learning path.</i></h2></div><p>Carefully crafted programmes for each stage of your market journey—from essential foundations to more advanced strategy work.</p></div><div className="courses-grid">{courses.map(([level, title, meta, image, description], index) => <article className="course-card" key={title}><div className="course-image"><img src={image} alt="" /><span>{level}</span><b>0{index + 1}</b></div><div className="course-body"><p className="course-meta">{meta}</p><h3>{title}</h3><p>{description}</p><a className="course-link" href="#disclaimer">Explore programme <ArrowRight size={16} /></a></div></article>)}</div></section>
    <section className="cta-section"><div className="cta-grid"><div><p className="eyebrow"><span /> Start with clarity</p><h2>Make room for a<br /><i>better market process.</i></h2></div><div><p>Explore the research service or learning programme that fits where you are today. No shortcuts—just a more structured way to engage with the markets.</p><a className="button button-light" href="#services">View all services <ArrowRight /></a></div></div><div className="cta-graphic" aria-hidden="true">RN</div></section>
    <footer id="disclaimer" className="footer section-shell"><Brand /><div className="footer-grid"><p>Rajesh Nivesh provides research and education designed to support informed market participation.</p><p><strong>Important:</strong> Investments in securities market are subject to market risks. Read all the related documents carefully before investing. Past performance is not indicative of future results.</p><p>SEBI Registered Research Analyst<br />Registration No. INH000026628</p></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Rajesh Nivesh. All rights reserved.</span><span>Privacy · Terms · Disclosures</span></div></footer>
  </main>;
}
